from typing import Dict, Any

def generate_explainable_report(analysis_results: Dict[str, Any]) -> str:
    """
    Generates a premium report with an explicit 'Reasoning Trace' for explainability.
    Neutral version (Location Removed).
    """
    battery_id = analysis_results.get("battery_id", "Unknown")
    soh = analysis_results.get("soh", 0.0)
    rul = analysis_results.get("adjusted_rul", 0.0)
    grade = analysis_results.get("grade", "N/A")
    hazards = analysis_results.get("is_hazardous", False)
    reasoning = analysis_results.get("reasoning_path", "No reasoning trace generated.")
    llm_recommendation = analysis_results.get("llm_recommendation", "")

    hazard_status = "🚨 HAZARDOUS" if hazards else "✅ SAFE"
    
    report = f"""
# 🔋 Battery Health Assessment Report: {battery_id}

## 📊 Summary Metrics
- **State of Health (SoH):** **{soh:.2f}%**
- **Predicted RUL:** **{rul:.2f} cycles**
- **Assigned Grade:** **{grade}**
- **Safety Status:** {hazard_status}

## 🧠 Expert Logic Trace (Explainability)
{reasoning}

## 💡 Agent Recommendation
{llm_recommendation}

---
*Generated by the Battery Health Assessment Agentic AI*
"""
    return report.strip()
